ci:
  skip:
    - golangci-lint
    - golangci-lint-config-verify

repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.59.1
    hooks:
      - id: golangci-lint
        entry: |
          bash -c '
            fd go.mod . \
            | xargs dirname \
            | xargs -I{} bash -c \
              "cd {} && golangci-lint run --config ../.golangci.yaml"
          '
        
      - id: golangci-lint-config-verify
