name: golangci-lint
on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  detect-modules:
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.set-modules.outputs.modules }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "modules=$(\
              find . -name go.mod \
              | xargs dirname \
              | jq --raw-input \
              | jq --slurp --compact-output \
          )" >> $GITHUB_OUTPUT
        id: set-modules
  golangci:
    name: lint
    runs-on: ubuntu-latest
    needs: detect-modules
    strategy:
      matrix: 
        modules: ${{ fromJSON(needs.detect-modules.outputs.modules) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61
          working-directory: ${{ matrix.modules }}
