name: Pulumi preview
on:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pulumi/auth-actions@v1
        with:
          organization: znd4
          requested-token-type: urn:pulumi:token-type:access_token:personal
          scope: user:znd4

      - uses: pulumi/actions@v5
        with:
          command: preview
          stack-name: znd4/dns/dns
          work-dir: dnsimple
